### ISSUE TITLE
Development of Use Case Diagram

### ISSUE THREAD

**Issue by tasnia87** [jkyleowens/Intro-SE-Group-5#6]

**Comment by DJKYL64** [comment]
### User:
The user should have access to the bookstore, but not as much as the admin does, by being able to register and log in, browse the book catalog, and go into the shopping cart and checkout.

### Admin:
The admin should have full access to the bookstore, as well as the ability to add and remove books to and from inventory, apply sales to any books in inventory, and monitor the transactions of every active account in the bookstore.

### Guest:
The guest should have limited access to the bookstore by being able to browse book catalog and inventory, but not be able to purchase anything or add anything to shopping cart without being able to sign in.
